version: "3.8"

services:
  ipmi-gpu-monitor:
    build: .
    image: ghcr.io/hrtsv/ipmi-gpu-monitor:main
    container_name: ipmi-gpu-monitor
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - IPMI_HOST=your_ipmi_host
      - IPMI_USERNAME=your_ipmi_username
      - IPMI_PASSWORD=your_ipmi_password
    volumes:
      - /opt/stacks/ipmi-gpu-monitor/data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "1", "--threads", "1", "run:app"]
    networks:
      - dockge_default
      - openwebui_default
      - searxng_searxng
      - tika_default

networks:
  dockge_default:
    external: true
  openwebui_default:
    external: true
  searxng_searxng:
    external: true
  tika_default:
    external: true