version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - SECRET_KEY=your_secret_key_here
      - JWT_SECRET_KEY=your_jwt_secret_key_here
      - IPMI_HOST=your_ipmi_host
      - IPMI_USERNAME=your_ipmi_username
      - IPMI_PASSWORD=your_ipmi_password
    devices:
      - /dev/ipmi0:/dev/ipmi0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
